### ISSUE TITLE
SourceRank

### ISSUE THREAD

**Issue by zeke** [librariesio/documentation#11]
I really like what SourceRank is turning out to be: a real manifestation of an idea that so many people have talked about for so long but nobody seems to have really followed through with. So congrats on pushing the concept forward.

I notice that for certain metrics like "Dependent Projects", the value is derived from "Logarithmic scale times two"...

I'd love to understand the motivations for these choices. Are the SourceRank "formulae" codified somewhere, or is the libraries.io codebase the best place to look?

<img width="839" alt="screen shot 2017-02-08 at 4 39 38 pm" src="https://cloud.githubusercontent.com/assets/2289/22764176/de768400-ee1d-11e6-94d1-79ea530bf7a4.png">

**Comment by BenJam** [comment]
I'm massively for this and I think I will default to @andrew to elaborate for the moment but any thinking on extending this will be more open and our rationale will be shared. It's something I've been working on for 2+ years quietly, which may be me falling on my own 🗡
