### ISSUE TITLE
Add rake task to generate package manager support matrix

### ISSUE THREAD

**Issue by BenJam** [librariesio/documentation#28]
There are three sources of data for supported package managers:

* the wiki (librariesio/libraries.io/wiki)
* the documentation (librariesio/documentation)
* the `pages/_matrix` partial resolver in librariesio/libraries.io (which read from `models/package managers`)

the best source is the latter. We should

- [x] build a rake task to generate supported package managers as a markdown table
- [x] delete the wiki page

**Comment by andrew** [comment]
Updated the wiki page to point to the docs page: https://github.com/librariesio/libraries.io/wiki/Package-Managers
