### ISSUE TITLE
Make a GitHub robot

### ISSUE THREAD

**Issue by fulldecent** [librariesio/documentation#48]
Rather than getting emails from you, I'd like to have a GitHub robot that will submit a PR updating my project's dependencies.

**Comment by fulldecent** [comment]
Ping @andrew @waldyrious could you please advise if this idea is reported to the correct place?

If it is then would a project that implements this idea be accepted into libraries.io?

**Comment by andrew** [comment]
Sorry for the delay, didn't see this issue, best place to open issues is over here: https://github.com/librariesio/libraries.io/issues

I've actually already put something together that should do most of what you're looking for over here: https://github.com/librariesio/lib2pr

**Comment by fulldecent** [comment]
Very cool, thanks for sharing. Closing this issue here.
