### ISSUE TITLE
conributor handbook

### ISSUE THREAD

**Issue by BenJam** [librariesio/documentation#5]
Following in the footsteps of organisations like GitLab it would be good for the core team to publish guidance on how we work, as if the team were 100 strong. 

We believe that this will attract contributors, make contributors more effective, motivate the core team to work as we ask contributors to work (openly and transparently) and ease the process for expanding the core team and/or offering payment for contributions.

A Contributor handbook should offer an introduction covering the project's culture (philosophies), then include topic based guidance such as:

* how should I use this handbook?
* how should I communicate?
* what tools should I use?
* what tools should I *not* use?
* what does the contributor workflow look like?
* how can I get assistance?
* what's it like working remotely and what challenges might I face?

What we should then do is hand off to other pages. See #2 #4 #3

**Comment by andrew** [comment]
👍
