### ISSUE TITLE
Draw libraries.io's architecture

### ISSUE THREAD

**Issue by BenJam** [librariesio/documentation#6]
It would be great to show how libraries.io works, where each of the black boxes fit together and which repo corresponds to each black box. This should be done twice for a non-technical audience (see #4) and a technical audience (see #3)

**Comment by andrew** [comment]
Probably should split out the difference between infrastructure diagram and the code architecture too.

**Comment by BenJam** [comment]
Closed in https://github.com/librariesio/documentation/commit/6c1775ed38838cc204470dced0ac56e0f5843214
