### ISSUE TITLE
Codify the developer workflow

### ISSUE THREAD

**Issue by BenJam** [librariesio/documentation#7]
While it's important that we have a workflow able to process *any* type of contribution, in reality many of those contributions will be code or will have to depend on code. Therefore it might make the most sense to hang the general case from the case that leads to code. 

Note that this is specifically not about what to work on and how to make decisions, just the workflow from the point of having a task that you'd like to work on. Much of this may come from the existing guidance on librariesio/libraries.io's README.md

**Comment by andrew** [comment]
Agreed, most contributions should start with an issue or thread in slack, then code/documentation changes proposed via pull requests to be reviewed, which then get merged and deployed by core team.

We could use the issue and pull request templates to help encourage good practises: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by BenJam** [comment]
OOI would we consider https://github.com/librariesio/documentation/commit/e980982c16468c774462da2f5f7683f5effd1bff to cover the developer workflow?

**Comment by andrew** [comment]
👍
