### ISSUE TITLE
Add specific documentation for adding a new registry 

### ISSUE THREAD

**Issue by BenJam** [librariesio/documentation#9]
It should be possibly for a contributor with knowledge of a specific registry and knowledge of the work distributed by that registry (language, framework etc) to easily add support for it. This will involve:

* explicitly publishing a 'generic' model with mandatory and optional data for use by other services
* publishing this with step by step guidance for submitting the new parser
* linking to guidance from librariesio/libraries.io#48

**Comment by andrew** [comment]
The specifics of adding the new registries can be in `/docs` of https://github.com/librariesio/libraries.io but we'll want some more generic picture of the standardized mapping documented in this repo too
